@hostname = http://127.0.0.1:5000/api

###

//Get Customer by Id

GET {{hostname}}/customer/c2
Content-Type: application/json

###

//Add New Customer

POST {{hostname}}/customer
Content-Type: application/json

{ "id": "c2", "name": "Abhishek Gupta" , "address":"Bangalore, India" , "phone": "432545"  }

###

//Add Account of a Customer

POST {{hostname}}/account
Content-Type: application/json

{ "id": "c2"}

###

//Update Customer

PUT {{hostname}}/customer
Content-Type: application/json

{ "id": "c1", "name": "Abhishek Kumar Gupta" , "address":"Delhi, India" , "phone": "25234524"  }

###

//Delete a Customer

DELETE  {{hostname}}/customer/c1
Content-Type: application/json

###

//Deposit Money

POST {{hostname}}/transaction/deposit
Content-Type: application/json

{ "id": "ac-0-c1", "amount": 12 }

###

//Withdraw Money

POST {{hostname}}/transaction/withdraw
Content-Type: application/json

{ "id": "acc-0-1", "amount": 5 }

###

//View Balance

GET {{hostname}}/transaction/checkbalance/acc-0-1
